# -*- coding: utf-8 -*-
"""星表扩容生成器（§0.42）——替代丢失的 gen-catalog.mjs。

数据源：VizieR V/50 Bright Star Catalogue（bsc5_catalog.dat，9110 星，J2000）。
- 现有 919 颗亮星（真 HIP 号，含中文名/星座）原值 100% 保留、顺序不变；
- 新增 BSC5 中 Vmag<=6.5 的星：hip = -HR（负号标记 BSC5/HR 编号，与正 HIP 零冲突），
  name=""，con=""（不参与星座连线/标签；星座名由 919 亮星提供）；
- 总量约 9.3k 颗；生成 4 个 part 文件 + StarCatalogData.kt 组装；
- constellationLines 下标按"HIP 定位"重映射到新列表（顺序无关）。
用法: python gen_catalog_hip.py
"""
import os
import re

BASE = r'C:\starcam-bundle\code\app\src\main\java\com\starcam\astro\astro'
CATALOG_FILE = os.path.join(BASE, 'StarCatalogData.kt')
BSC5_FILE = r'C:\dev\bsc5_catalog.dat'
MAG_LIMIT = 6.5
PARTS = 8

# ---------- 1. 解析现有星表（组装版：constellationLines 在 StarCatalogData.kt，
#   星数据在 StarCatalogPart*.kt；原 919 颗为正 hip，增补星为负 hip） ----------
with open(CATALOG_FILE, 'r', encoding='utf-8') as f:
    old_src = f.read()

star_re = re.compile(
    r'StarEntry\((\d+),\s*([\d.]+),\s*([-\d.]+),\s*([-\d.]+),\s*"([^"]*)",\s*"([^"]*)"\)'
)
old_stars = []
seen = set()
for p in range(1, 9):
    part_file = os.path.join(BASE, 'StarCatalogPart%d.kt' % p)
    if not os.path.exists(part_file):
        continue
    with open(part_file, 'r', encoding='utf-8') as f:
        for m in star_re.finditer(f.read()):
            hip = int(m.group(1))
            if hip > 120000 or hip in seen:  # 只取原 919（真 HIP <=118218 < 120000）
                continue
            seen.add(hip)
            old_stars.append({
                'hip': hip,
                'ra': float(m.group(2)),
                'dec': float(m.group(3)),
                'mag': float(m.group(4)),
                'name': m.group(5),
                'con': m.group(6),
            })
print('old stars:', len(old_stars))

line_re = re.compile(r'intArrayOf\((\d+),\s*(\d+)\)')
old_lines = [(int(a), int(b)) for a, b in line_re.findall(old_src)]
print('old constellation lines:', len(old_lines))
old_hip_by_idx = {i: s['hip'] for i, s in enumerate(old_stars)}
assert all(a < len(old_stars) and b < len(old_stars) for a, b in old_lines), '下标越界'
old_line_hips = [(old_hip_by_idx[a], old_hip_by_idx[b]) for a, b in old_lines]

# ---------- 2. 解析 BSC5 ----------
# 新星 hip = HR + 120000（HIP 主表编号上限 ~118218，加偏移保证与真 HIP 零冲突
# 且全表按 hip 升序，catalogIntegrity 的升序断言保持有效）
HIP_OFFSET = 120000

def parse_ra(line):
    rah = int(line[75:77]); ram = int(line[77:79]); ras = float(line[79:83])
    return 15.0 * (rah + ram / 60.0 + ras / 3600.0)

def parse_dec(line):
    sign = -1.0 if line[83:84] == '-' else 1.0
    ded = int(line[84:86]); dem = int(line[86:88]); des = float(line[88:90])
    return sign * (ded + dem / 60.0 + des / 3600.0)

new_stars = []
n_skip = 0
with open(BSC5_FILE, 'r', encoding='ascii', errors='replace') as f:
    for line in f:
        if len(line) < 107:
            n_skip += 1
            continue
        try:
            hr = int(line[0:4])
            vmag = float(line[102:107])
            ra = parse_ra(line)
            dec = parse_dec(line)
        except ValueError:
            n_skip += 1
            continue
        if vmag > MAG_LIMIT:
            continue
        # 只收暗星（4.5 < mag <= 6.5）：BSC5 与 HIP 不是同一星表，BSC5 独有
        # 的亮星（mag<=4.5）若混入会改变 buildIndex/catGrid/countInliers 的
        # 亮星域（实测 900 颗混入 → 索引域变化 → 匹配全崩），必须排除，
        # 让亮星域（mag<=4.5）严格保持原 919 不变。
        if vmag <= 4.5:
            continue
        new_stars.append({'hip': HIP_OFFSET + hr, 'ra': ra, 'dec': dec, 'mag': vmag,
                          'name': '', 'con': ''})
print('new stars (BSC5 mag<=%.1f):' % MAG_LIMIT, len(new_stars), 'skip:', n_skip)

# ---------- 3. 合并并统一按 hip 升序（保证 catalogIntegrity 升序断言） ----------
all_stars = list(old_stars) + new_stars
all_stars.sort(key=lambda s: s['hip'])
print('total stars:', len(all_stars))

# 唯一性
assert len({s['hip'] for s in all_stars}) == len(all_stars), 'hip 重复！'

new_idx_by_hip = {s['hip']: i for i, s in enumerate(all_stars)}

# ---------- 4. 生成 part 文件 ----------
def fmt_star(s):
    return '        StarEntry(%d, %.6f, %.6f, %.2f, "%s", "%s")' % (
        s['hip'], s['ra'], s['dec'], s['mag'], s['name'], s['con'])

part_size = (len(all_stars) + PARTS - 1) // PARTS
part_files = []
for p in range(PARTS):
    chunk = all_stars[p * part_size:(p + 1) * part_size]
    name = 'StarCatalogPart%d.kt' % (p + 1)
    part_files.append(name)
    with open(os.path.join(BASE, name), 'w', encoding='utf-8') as f:
        f.write('// generated by tools/gen_catalog_hip.py - DO NOT EDIT\n')
        f.write('package com.starcam.astro.astro\n\n')
        f.write('internal val starListPart%d: List<StarEntry> = listOf(\n' % (p + 1))
        for s in chunk:
            f.write(fmt_star(s) + ',\n')
        f.write(')\n')
    print('wrote', name, len(chunk))

# ---------- 5. 重写 StarCatalogData.kt ----------
new_lines = [(new_idx_by_hip[a], new_idx_by_hip[b]) for a, b in old_line_hips]
parts_expr = ' + '.join('starListPart%d' % (p + 1) for p in range(PARTS))

with open(CATALOG_FILE, 'w', encoding='utf-8') as f:
    f.write('// This file is auto-generated by tools/gen_catalog_hip.py - DO NOT EDIT\n')
    f.write('package com.starcam.astro.astro\n\n')
    f.write('/** 星表条目（J2000 历元，赤经赤纬单位为度） */\n')
    f.write('class StarEntry(\n')
    f.write('    val hip: Int,\n')
    f.write('    val ra: Double,\n')
    f.write('    val dec: Double,\n')
    f.write('    val mag: Double,\n')
    f.write('    val name: String,\n')
    f.write('    val con: String\n')
    f.write(')\n\n')
    f.write('object StarCatalogData {\n\n')
    f.write('    /** 星表（视星等 <= %.1f，共 %d 颗；前 919 颗为原亮星含中文名/星座，' % (MAG_LIMIT, len(all_stars)))
    f.write('     *  其余为 BSC5 增补星（hip 为负 HR 号，无名字），按原顺序排列）*/\n')
    f.write('    val stars: List<StarEntry> = %s\n\n' % parts_expr)
    f.write('    /** 星座连线（下标对，指向 stars）——由生成器按 HIP 重映射 */\n')
    f.write('    val constellationLines: List<IntArray> = listOf(\n')
    for a, b in new_lines:
        f.write('        intArrayOf(%d, %d),\n' % (a, b))
    f.write('    )\n\n')
    f.write('    private val hipToIndex: Map<Int, Int> = stars.indices.associateBy { stars[it].hip }\n\n')
    f.write('    /** 按编号查星表下标（正=HIP，负=BSC5/HR），查不到返回 -1 */\n')
    f.write('    fun indexOfHip(hip: Int): Int = hipToIndex[hip] ?: -1\n')
    f.write('}\n')
print('rewrote', CATALOG_FILE)

# ---------- 6. 校验 ----------
missing = [s['hip'] for s in old_stars if s['hip'] not in new_idx_by_hip]
diff = []
for s in old_stars:
    ns = all_stars[new_idx_by_hip[s['hip']]]
    if (ns['ra'], ns['dec'], ns['mag'], ns['name'], ns['con']) != \
            (s['ra'], s['dec'], s['mag'], s['name'], s['con']):
        diff.append(s['hip'])
print('VERIFY missing_old_hip:', missing)
print('VERIFY value_diff_old_hip:', diff)
print('VERIFY line_endpoints_same:',
      old_line_hips == [(all_stars[a]['hip'], all_stars[b]['hip']) for a, b in new_lines])
